---
title: Desert Tropics Custom Pools
timezone: Arizona
collections:
  posts:
    title: Desert Tropics Blog Posts
    output: true
    permalink: /blog/:title/
defaults:
- scope:
    path: ""
    type: posts
  values:
    comments: true
- scope:
    path: ""
  values:
    layout: default
    show-avatar: true
gems:
- jekyll-feed
url: "/"
enforce_ssl: ""
baseurl: "/deserttropicspools"
description: Desert Tropics Custom Pools has been building pools in the Valley since 2001. Our President is also the Qualifying Party for our license. We don’t strive to build the most pools in the Valley, though we do strive to build the best pools in the Valley.
keywords: custom pool phoenix, Arizona custom pool builder, AZ pool builder, Custom pool builder AZ, Swimming pool design AZ, Custom swimming pools Paradise Valley, Custom swimming pools Scottsdale, Custom swimming pools Arizona, Custom swimming pools Phoenix, Custom pool and spa builder, Custom swimming pool designer Arizona, Pebble tec pools Arizona, Custom pool designer Arizona, Spa builder Arizona, Custom spas Arizona, Natural pools Arizona, Eco friendly pools Arizona, Custom pools phoenix, Award winning pools AZ, Pool remodeler Arizona, Negative edge pools, lazy rivers, Custom swimming pools Peoria, Custom swimming pools Surprise, Custom swimming pools Cave Creek, Custom swimming pools Glendale, Custom swimming pools Goodyear, Custom swimming pools Wadell, Custom swimming pools
desc: Desert Tropics Custom Pools
avatar: 'http://www.deserttropics.com/assets/images/desert-tropics-images/desert-tropics-avatar.png'
profile:
  name: Desert Tropics Custom Pools
  email: info@deserttropics.com
  facebook: //www.facebook.com/deserttropicspools/
  googleplus: //plus.google.com/111814675770550054157
  linkedin: //www.linkedin.com/company/desert-tropics-custom-pools
pretty-url: deserttropics.com
disqus: Your-Disqus-Id
google_analytics: Your-GA-Id
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
sass:
  load_paths:
    - bower_components/bootstrap-sass/assets/stylesheets
    - assets/css
  style: compressed
exclude:
  - node_modules
  - Gruntfile.js
  - package.json
  - vendor
created-by: David Manzer | G2 Design Lab
creator-url:
  exclude:
    - node_modules
styles:
  - default
  - white
  - black
development:
  asset_url: "http://127.0.0.1:4000/assets"
  app_url: "http://127.0.0.1:4000/"
